logging.config=classpath:logback-spring.xml

server.port=8084
#server.servlet.context-path=/empdb-mcp

spring.application.name=empdb-mcp
spring.ai.mcp.server.name=empdb-mcp-server
spring.ai.mcp.server.version=0.0.1

spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=sync

spring.datasource.seerworks.url=jdbc:postgresql://localhost:5432/employees?schema=employees
spring.datasource.seerworks.username=${DB_USER}
spring.datasource.seerworks.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect