package com.seerworks.db.mcp.empdb.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

/**
 * This service will be used by our tools to run the queries on the Employee DB,
 * once the query is generated by the LLM, the LLM will then run that query using this MCP.
 */
@Service
public class EmployeeDBService {
    private final JdbcTemplate seerWorksJdbcTemplate;
    private final Logger LOGGER = LoggerFactory.getLogger(EmployeeDBService.class);

    public EmployeeDBService(JdbcTemplate seerWorksJdbcTemplate) {
        this.seerWorksJdbcTemplate = seerWorksJdbcTemplate;
    }

    public String runQueryAndReturnJSONResults(String query) {
        String jsonAggQeury = "SELECT json_agg(row_to_json(t)) FROM (" + query + ") t";
        return this.seerWorksJdbcTemplate.queryForObject(jsonAggQeury, String.class);
    }

    public List<Map<String, Object>> runQueryAndReturnListOfMaps(String query) {
        try {
            if (!StringUtils.hasLength(query)) throw new RuntimeException("No Query defined");
            boolean containsForbiddenKeyword = Stream.of("INSERT", "DELETE", "UPDATE")
                    .anyMatch(query.toUpperCase()::contains);
            if (containsForbiddenKeyword) throw new RuntimeException("ONLY Select queries are allowed!!");
            List<Map<String, Object>> queryResults = this.seerWorksJdbcTemplate.queryForList(query);
            LOGGER.debug("The query results for query {} are {}", query, queryResults);
            return queryResults;
        } catch (Exception e) {
            LOGGER.error("The exception is " + e);
            throw new RuntimeException(e);
        }
    }
}
